version: '3'

services:

  ead-authuser:
    image: postgres:latest
    container_name: ead-authuser
    networks:
      - ead
    environment:
      - POSTGRES_DB=ead-authuser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    ports:
      - 5432:5432

  ead-authuser-v2:
    image: postgres:latest
    container_name: ead-authuser-v2
    networks:
      - ead
    environment:
      - POSTGRES_DB=ead-authuser-v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    ports:
      - 5442:5432

  ead-course:
    image: postgres:latest
    container_name: ead-course
    networks:
      - ead
    environment:
      - POSTGRES_DB=ead-course
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    ports:
      - 5433:5432

  ead-course-v2:
    image: postgres:latest
    container_name: ead-course-v2
    networks:
      - ead
    environment:
      - POSTGRES_DB=ead-course-v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    ports:
      - 5443:5432

networks:
  ead:
    driver: bridge