server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://ead-authuser-service
            predicates:
              - Path=/ead-authuser/**
          - id: course-service
            uri: lb://ead-course-service
            predicates:
              - Path=/ead-course/**

# API GTW vai se registrar e vai conseguir descobrir os de mais microservices
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost